# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{documenter}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["A N"]
  s.date = %q{2009-12-11}
  s.description = %q{This gem uses OpenOffice and pdftk to convert, split, join, fill and copy files. It may be usefull if you have many documents to work with. It is not realy fast solution and it depend on istalled software}
  s.email = %q{goremika@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "documenter.gemspec",
     "lib/documenter.rb",
     "lib/documenter/csv.rb",
     "lib/documenter/ooo.rb",
     "lib/documenter/ooo/converter.rb",
     "lib/documenter/ooo/jod/ChangeLog.txt",
     "lib/documenter/ooo/jod/LICENSE.txt",
     "lib/documenter/ooo/jod/README.txt",
     "lib/documenter/ooo/jod/docs/jodconverter-2.2.2-javadoc.jar",
     "lib/documenter/ooo/jod/docs/third-party-licenses/license-commons-io.txt",
     "lib/documenter/ooo/jod/docs/third-party-licenses/license-openoffice.org.txt",
     "lib/documenter/ooo/jod/docs/third-party-licenses/license-slf4j.txt",
     "lib/documenter/ooo/jod/docs/third-party-licenses/license-xstream.txt",
     "lib/documenter/ooo/jod/document-formats.xml",
     "lib/documenter/ooo/jod/lib/DEPENDENCIES.txt",
     "lib/documenter/ooo/jod/lib/commons-cli-1.2.jar",
     "lib/documenter/ooo/jod/lib/commons-io-1.4.jar",
     "lib/documenter/ooo/jod/lib/jodconverter-2.2.2.jar",
     "lib/documenter/ooo/jod/lib/jodconverter-cli-2.2.2.jar",
     "lib/documenter/ooo/jod/lib/juh-3.0.1.jar",
     "lib/documenter/ooo/jod/lib/jurt-3.0.1.jar",
     "lib/documenter/ooo/jod/lib/ridl-3.0.1.jar",
     "lib/documenter/ooo/jod/lib/slf4j-api-1.5.6.jar",
     "lib/documenter/ooo/jod/lib/slf4j-jdk14-1.5.6.jar",
     "lib/documenter/ooo/jod/lib/unoil-3.0.1.jar",
     "lib/documenter/ooo/jod/lib/xstream-1.3.1.jar",
     "lib/documenter/ooo/jod/src/jodconverter-2.2.2-sources.jar",
     "lib/documenter/ooo/jod/src/jodconverter-cli-2.2.2-sources.jar",
     "lib/documenter/ooo/odf.rb",
     "lib/documenter/ooo/odt.rb",
     "lib/documenter/pdf.rb",
     "lib/documenter/pdftk/790_44.pdf",
     "lib/documenter/pdftk/doc_data.txt",
     "lib/documenter/pdftk/pdftk.exe",
     "lib/documenter/pdftk/readme.txt",
     "myout.csv",
     "out/jod/ChangeLog.txt",
     "out/jod/LICENSE.txt",
     "out/jod/README.txt",
     "out/jod/docs/jodconverter-2.2.2-javadoc.jar",
     "out/jod/docs/third-party-licenses/license-commons-io.txt",
     "out/jod/docs/third-party-licenses/license-openoffice.org.txt",
     "out/jod/docs/third-party-licenses/license-slf4j.txt",
     "out/jod/docs/third-party-licenses/license-xstream.txt",
     "out/jod/document-formats.xml",
     "out/jod/lib/DEPENDENCIES.txt",
     "out/jod/lib/commons-cli-1.2.jar",
     "out/jod/lib/commons-io-1.4.jar",
     "out/jod/lib/jodconverter-2.2.2.jar",
     "out/jod/lib/jodconverter-cli-2.2.2.jar",
     "out/jod/lib/juh-3.0.1.jar",
     "out/jod/lib/jurt-3.0.1.jar",
     "out/jod/lib/ridl-3.0.1.jar",
     "out/jod/lib/slf4j-api-1.5.6.jar",
     "out/jod/lib/slf4j-jdk14-1.5.6.jar",
     "out/jod/lib/unoil-3.0.1.jar",
     "out/jod/lib/xstream-1.3.1.jar",
     "out/jod/src/jodconverter-2.2.2-sources.jar",
     "out/jod/src/jodconverter-cli-2.2.2-sources.jar",
     "out/pdftk/790_44.pdf",
     "out/pdftk/doc_data.txt",
     "out/pdftk/pdftk.exe",
     "out/pdftk/readme.txt",
     "test/helper.rb",
     "test/test_documenter.rb"
  ]
  s.homepage = %q{http://github.com/goremika/documenter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{api to some tools to work with documetns}
  s.test_files = [
    "test/helper.rb",
     "test/test_documenter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.2"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0.8.2"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0.8.2"])
  end
end

